pod 'SwiftyJSON'# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CurrencyConverter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CurrencyConverter
pod 'Charts', :inhibit_warnings => true
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'DropDown', :inhibit_warnings => true
inhibit_all_warnings!
end
