# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CurrencyConverter2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CurrencyConverter2
pod 'DropDown'
pod 'Charts'
pod 'Alamofire'

end
